#!/usr/bin/env npx ts-node

/**
 * Import CSV Template Data to Service Catalog
 * 
 * Imports the analyzed template.csv and hd_template.csv data into the service catalog
 * for testing dynamic field templates and static service templates.
 */

import { PrismaClient } from '@prisma/client';
import fs from 'fs';
import path from 'path';

const prisma = new PrismaClient();

interface TemplateMapping {
  dynamicTemplates: any[];
  staticTemplates: any[];
  fieldTypeMappings: any;
  departmentAssignments: any;
  statistics: any;
}

async function main() {
  console.log('📥 Importing CSV Template Data to Service Catalog...\n');

  try {
    // Read the template mapping generated by analyze-csv-templates.ts
    const mappingPath = path.join(__dirname, '../template-mapping.json');
    if (!fs.existsSync(mappingPath)) {
      console.error('❌ Template mapping file not found. Run analyze-csv-templates.ts first.');
      process.exit(1);
    }

    const mapping: TemplateMapping = JSON.parse(fs.readFileSync(mappingPath, 'utf8'));
    console.log(`📊 Loaded mapping: ${mapping.statistics.totalTemplates} templates\n`);

    // Phase 1: Create/verify IT Operations department
    const itDepartment = await prisma.department.upsert({
      where: { id: 1 },
      update: {},
      create: {
        id: 1,
        name: 'IT Operations',
        description: 'Information Technology Operations Department'
      }
    });

    console.log(`✅ IT Operations Department: ${itDepartment.name} (ID: ${itDepartment.id})\n`);

    // Phase 2: Create parent service catalog categories
    const parentServiceCatalogs = [
      { name: 'OLIBS System', description: 'Online Banking System templates and services' },
      { name: 'BSG Applications', description: 'BSG mobile and web application services' },
      { name: 'ATM Management', description: 'ATM hardware and transaction services' },
      { name: 'Core Banking', description: 'Core banking system and financial services' },
      { name: 'Network & Infrastructure', description: 'Network connectivity and infrastructure services' },
      { name: 'Security & Access', description: 'Security management and user access services' },
      { name: 'Claims & Transactions', description: 'Payment claims and transaction processing' },
      { name: 'Hardware & Software', description: 'Hardware maintenance and software applications' }
    ];

    console.log('📂 Creating parent service catalogs...');
    const createdServiceCatalogs = new Map<string, any>();

    for (const catalogData of parentServiceCatalogs) {
      const serviceCatalog = await prisma.serviceCatalog.upsert({
        where: { 
          departmentId_name: {
            departmentId: itDepartment.id,
            name: catalogData.name
          }
        },
        update: { 
          description: catalogData.description 
        },
        create: {
          name: catalogData.name,
          description: catalogData.description,
          departmentId: itDepartment.id,
          serviceType: 'business_service',
          categoryLevel: 1,
          isActive: true
        }
      });
      createdServiceCatalogs.set(catalogData.name, serviceCatalog);
      console.log(`   ✅ ${serviceCatalog.name}`);
    }

    // Phase 3: Import dynamic field templates (24 templates from template.csv)
    console.log('\n⚡ Importing dynamic field templates from template.csv...');
    let dynamicCount = 0;

    for (const template of mapping.dynamicTemplates) {
      // Determine parent service catalog based on application
      let parentServiceCatalogName = 'BSG Applications'; // Default
      if (template.application === 'OLIBS') parentServiceCatalogName = 'OLIBS System';
      else if (template.application.includes('ATM')) parentServiceCatalogName = 'ATM Management';
      else if (template.application.includes('XCARD')) parentServiceCatalogName = 'Core Banking';

      const parentServiceCatalog = createdServiceCatalogs.get(parentServiceCatalogName);
      
      // Create service item for this application
      const serviceItem = await prisma.serviceItem.upsert({
        where: { 
          serviceCatalogId_name: {
            serviceCatalogId: parentServiceCatalog.id,
            name: `${template.application} Templates`
          }
        },
        update: {
          description: `Dynamic templates for ${template.application} services`
        },
        create: {
          name: `${template.application} Templates`,
          description: `Dynamic templates for ${template.application} services`,
          serviceCatalogId: parentServiceCatalog.id,
          requestType: 'service_request',
          isActive: true,
          sortOrder: 1
        }
      });

      // Create the service template
      const serviceTemplate = await prisma.serviceTemplate.upsert({
        where: {
          serviceItemId_name: {
            serviceItemId: serviceItem.id,
            name: template.serviceType
          }
        },
        update: {
          description: `${template.application} - ${template.serviceType}`
        },
        create: {
          name: template.serviceType,
          description: `${template.application} - ${template.serviceType}`,
          serviceItemId: serviceItem.id,
          templateType: 'standard',
          isVisible: true,
          sortOrder: parseInt(template.templateNumber) || 1,
          estimatedResolutionTime: 24 // 24 hours default
        }
      });

      // Create dynamic fields for this template
      for (let i = 0; i < template.fields.length; i++) {
        const field = template.fields[i];
        
        // Map CSV field type to system field type
        let fieldType: any = 'text';
        if (field.type.includes('Date')) fieldType = 'date';
        else if (field.type.includes('Drop-Down')) fieldType = 'dropdown';
        else if (field.type.includes('Short Text')) fieldType = 'text';
        else if (field.type.includes('Number')) fieldType = 'number';
        else if (field.type.includes('Currency')) fieldType = 'number';
        else if (field.type.includes('Timestamp')) fieldType = 'datetime';
        else if (field.type.includes('Text')) fieldType = 'textarea';

        await prisma.serviceFieldDefinition.upsert({
          where: {
            serviceTemplateId_fieldName: {
              serviceTemplateId: serviceTemplate.id,
              fieldName: field.name
            }
          },
          update: {
            fieldType: fieldType,
            isRequired: field.isRequired
          },
          create: {
            serviceTemplateId: serviceTemplate.id,
            fieldName: field.name,
            fieldLabel: field.name,
            fieldType: fieldType,
            isRequired: field.isRequired,
            placeholder: field.description,
            sortOrder: i + 1,
            validationRules: field.maxLength ? { maxLength: field.maxLength } : undefined
          }
        });
      }

      dynamicCount++;
      console.log(`   ✅ ${template.application} - ${template.serviceType} (${template.fields.length} fields)`);
    }

    // Phase 4: Import static service templates (247 templates from hd_template.csv)
    console.log('\n📋 Importing static service templates from hd_template.csv...');
    let staticCount = 0;
    const processedServiceItems = new Set<string>();

    for (const template of mapping.staticTemplates) {
      // Determine parent service catalog
      let parentServiceCatalogName = 'Hardware & Software'; // Default
      if (template.category.includes('OLIBs')) parentServiceCatalogName = 'OLIBS System';
      else if (template.category.includes('BSG')) parentServiceCatalogName = 'BSG Applications';
      else if (template.category.includes('ATM')) parentServiceCatalogName = 'ATM Management';
      else if (template.category.includes('Kasda') || template.category.includes('XCARD')) parentServiceCatalogName = 'Core Banking';
      else if (template.category.includes('Network') || template.category.includes('Internet')) parentServiceCatalogName = 'Network & Infrastructure';
      else if (template.category.includes('Domain') || template.category.includes('Password')) parentServiceCatalogName = 'Security & Access';

      const parentServiceCatalog = createdServiceCatalogs.get(parentServiceCatalogName);
      
      // Create service item for this template category
      const serviceItemName = template.category;
      const serviceItemKey = `${parentServiceCatalog.id}-${serviceItemName}`;
      
      if (!processedServiceItems.has(serviceItemKey)) {
        await prisma.serviceItem.upsert({
          where: { 
            serviceCatalogId_name: {
              serviceCatalogId: parentServiceCatalog.id,
              name: serviceItemName
            }
          },
          update: {
            description: `Service templates for ${template.category}`
          },
          create: {
            name: serviceItemName,
            description: `Service templates for ${template.category}`,
            serviceCatalogId: parentServiceCatalog.id,
            requestType: 'service_request',
            isActive: true,
            sortOrder: 1
          }
        });
        processedServiceItems.add(serviceItemKey);
      }

      const serviceItem = await prisma.serviceItem.findFirst({
        where: {
          serviceCatalogId: parentServiceCatalog.id,
          name: serviceItemName
        }
      });

      // Create the service template
      await prisma.serviceTemplate.upsert({
        where: {
          serviceItemId_name: {
            serviceItemId: serviceItem!.id,
            name: template.name
          }
        },
        update: {
          description: template.description
        },
        create: {
          name: template.name,
          description: template.description || `Service template for ${template.name}`,
          serviceItemId: serviceItem!.id,
          templateType: 'standard',
          isVisible: true,
          sortOrder: staticCount + 1,
          estimatedResolutionTime: 24 // 24 hours default
        }
      });

      staticCount++;
      if (staticCount % 50 === 0) {
        console.log(`   📊 Processed ${staticCount}/${mapping.staticTemplates.length} static templates...`);
      }
    }

    console.log(`   ✅ All ${staticCount} static templates imported\n`);

    // Phase 5: Summary and verification
    const totalServiceTemplates = await prisma.serviceTemplate.count();
    const totalServiceCatalogs = await prisma.serviceCatalog.count();
    const totalServiceItems = await prisma.serviceItem.count();
    const totalFields = await prisma.serviceFieldDefinition.count();

    console.log('📊 Import Summary:');
    console.log(`   🎯 Total Service Templates: ${totalServiceTemplates}`);
    console.log(`   📂 Total Service Catalogs: ${totalServiceCatalogs}`);
    console.log(`   📁 Total Service Items: ${totalServiceItems}`);
    console.log(`   ⚡ Total Dynamic Fields: ${totalFields}`);
    console.log(`   📋 Dynamic Templates: ${dynamicCount}`);
    console.log(`   📄 Static Templates: ${staticCount}`);

    console.log('\n✨ CSV template data successfully imported to service catalog!');
    console.log('🔍 Ready for MCP Playwright testing with all 271 templates available.\n');

    // Update the checklist with completion status
    console.log('📋 Updating validation checklist...');
    const checklistPath = path.join(__dirname, '../../SERVICE_CATALOG_TEMPLATE_VALIDATION_CHECKLIST.md');
    let checklist = fs.readFileSync(checklistPath, 'utf8');
    
    // Mark import phases as completed
    checklist = checklist.replace(
      '- [ ] **CSV Data Analysis** (Analysis complete)',
      '- [x] **CSV Data Analysis** (✅ Analysis complete - 271 templates found)'
    );
    checklist = checklist.replace(
      '- [ ] **Service Catalog Import** (Import to database)',
      '- [x] **Service Catalog Import** (✅ 271 templates imported to database)'
    );
    
    fs.writeFileSync(checklistPath, checklist);
    console.log('✅ Validation checklist updated');

  } catch (error) {
    console.error('❌ Error importing CSV template data:', error);
    process.exit(1);
  } finally {
    await prisma.$disconnect();
  }
}

main().catch((error) => {
  console.error('Fatal error:', error);
  process.exit(1);
});